/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main_F103.h"
#include "GPIO.h"
#include "CAN.h"

CAN_Config SLAVE1;
CAN_TX_Typedef SLAVE1_TX;
CAN_RX_Typedef SLAVE1_RX;
CAN_Filter_TypeDef SLAVE1_filter;

void CAN1_RX0_IRQHandler(void);

bool flag = 0;

int main(void)
{
	MCU_Clock_Setup();

	SLAVE1.CAN_INSTANCE = CAN1;
	SLAVE1.RX_Pin = CAN_Pin.RX.PA11;
	SLAVE1.TX_Pin = CAN_Pin.TX.PA12;
	SLAVE1.Baudrate = CAN_Baudrate.CAN_BAUDRATE_1000_KBPS;
	SLAVE1.interrupt = CAN_Interrupt.Fifo0_Message_Pending;
	CAN_Init(&SLAVE1);

	SLAVE1_filter.ID = 0x00;
	SLAVE1_filter.filter_id = 0;
	SLAVE1_filter.id_type = CAN_ID.Standard;
	SLAVE1_filter.frame_type = CAN_Frame.Data_Frame;
	CAN_Filter_Init(&SLAVE1, &SLAVE1_filter);
	CAN_Start(&SLAVE1);

	__disable_irq();
	NVIC_SetPriority(CAN1_RX0_IRQn,0);
	NVIC_EnableIRQ(CAN1_RX1_IRQn);
	__enable_irq();




	for(;;)
	{
		if(flag == 1)
		{
			CAN_Get_Packet(&SLAVE1, &SLAVE1_RX);


			flag = 0;
		}

	}
}



void CAN1_RX0_IRQHandler(void)
{
	flag = 1;



}
